apiVersion: v1
kind: Service
metadata:
  name: medical-records-service
spec:
  type: NodePort
  selector:
    app: medical-records-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
