apiVersion: v1
kind: Service
metadata:
  name: medical-records-service
  namespace: cognivita
spec:
  type: NodePort
  selector:
    app: medical-records-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
