apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: cognivita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: monta2027/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_HOSTNAME
              value: "eureka-server"
