apiVersion: v1
kind: Service
metadata:
  name: medication-adherence-service
  namespace: cognivita
spec:
  selector:
    app: medication-adherence-service
  ports:
    - port: 8086
      targetPort: 8086
