apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cognivita
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30087
~
