apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-prevention-service
  namespace: cognivita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-prevention-service
  template:
    metadata:
      labels:
        app: health-prevention-service
    spec:
      containers:
        - name: health-prevention-service
          image: monta2027/health-prevention-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "mysql-medical"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "health_prevention_db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medical-records-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_HOST
              value: "eureka-server"
            - name: MEDICAL_RECORDS_URL
              value: "http://medical-records-service:8081"
